AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
  DisplayCopNames: true

Style/AndOr:
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    detect: "detect"
    find: "detect"

Style/DeprecatedHashMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/EmptyElse:
  EnforcedStyle: empty

Style/FormatString:
  EnforcedStyle: percent

Style/GuardClause:
  MinBodyLength: 5

Style/IfUnlessModifier:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/Lambda:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Style/PredicateName:
  NamePrefixBlacklist:
    - "is_"
    - "have_"
  NamePrefix:
    - "is_"
    - "have_"

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceAroundOperators:
  MultiSpaceAllowedForOperators:
    - "="
    - "=>"
    - "||"

Style/SingleLineBlockParams:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120

Metrics/PerceivedComplexity:
  Max: 8